// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int NumTest = Integer.parseInt(args[0]);
	int CounterU = 0 ;
	int CounterD = 0;
	double SumTest = 0;
	for (int i =0 ;i < NumTest ; i ++){
		double RandomNum = Math.random();

		if (RandomNum > 0.5) {
			CounterU ++ ; 
		}else {
			CounterD ++;
		}
		SumTest += RandomNum;
 

	}
		SumTest = SumTest / (double) NumTest;

	System.out.printf("> 0.5: %d times\n<= 0.5: %d times\nRatio: %.2f\n", CounterU, CounterD, SumTest);


	    // Replace this comment with your code
	}
}
